### ISSUE TITLE
Flow to import historical live data

### ISSUE THREAD

**Issue by vekexasia** [themonomers/tesla#2]
Hello, first of all nice work.

I would likle to import live telemetry  historical data. to process information and adopt a energy effifient strategy to pay less energy bills.

Let me better explain my needs. There is a energy provider offer that lets you withdraw as much as you can for free for 3 hours every day.

My goal is to understand what would be the best hours to provide the energy provider in order to minimize the cost. To do so I would like to gather hourly statistics since March 2021 so that I can check at what time my powerwall ran out of juice the most. The plan then is to get the powerwall to charge up to 100% again and turn on other stuff like home heating so that i can preserve heating for the day.

Before i start digging into it what would you recommend?

**Comment by themonomers** [comment]
Hi!  To find out when your powerwall ran out of juice, I would suggest using the `getBatteryChargeHistory(period, date)` function in TeslaEnergyAPI.py.  I would pass period, 'day' and setup a for loop for each day from March 1, 2021 until today.  In that loop I would dump that into a Google Sheet and then you can easily run a pivot table of when your powerwall state of charge reached 0.

This will be a lot of data (15 minute increments) but I think you'll want that granularity because you're trying to figure out the most common time it reaches zero.  You could, of course, just write the hourly values and skip the other values to save on space/rows.

**Comment by vekexasia** [comment]
Thanks for the tip @themonomers, i'm trying also to re-implement the good work you made here on my nodejs library to interact with Tesla Powerwall's api. 

Any idea why your `getSiteTOUHistory` would return empty response? I'm querying wiht the following params:

```
{
  end_date: '2022-08-23T23:59:59+02:00',
  kind: 'time_of_use_energy',
  period: 'day',
  start_date: '2022-08-23T00:00:00+02:00'
}
```

**Comment by themonomers** [comment]
Hi!  Two possibilities come to mind:

1.  The API only accepts the `start_date` and `end_date` in GMT.  So you need to take your date/time and convert it.  Using my time zone as an example, Pacific, to get yesterday's data:

`https://owner-api.teslamotors.com/api/1/energy_sites/xxxxx/calendar_history?kind=time_of_use_energy&period=day&start_date=2022-08-25T07:00:00Z&end_date=2022-08-26T06:59:59Z`

2.  I've noticed that when my system switches to self-powered, it somehow corrupts the data for those days such that it returns an empty JSON.

Hope that helps!
